# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 04:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170905_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventtype',
        ),
        migrations.RemoveField(
            model_name='event',
            name='requestor',
        ),
        migrations.RemoveField(
            model_name='event',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='event',
            name='userid',
        ),
        migrations.AddField(
            model_name='event',
            name='InventoryRTeMinVertClearance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='InventoryRteTotalHorzClearance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='STRAHNETHighwayDesignation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='approachRoadwayAlignment',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='approachRoadwayWidth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='averageDailyTraffic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='avgDailyTruckTraffic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='baseHighwayPoint',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='borderBridge',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='event',
            name='borderBridgeStructureNumber',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='event',
            name='bridgeImprovementCost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='bridgeMedian',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='bridgePosting',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='bridgeRoadwayWithCurbToCurb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='bypassDetourLength',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='channelChannelProtection',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='countyCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='criticalFeatureInspection',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='event',
            name='criticalFeatureInspectionDates',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='event',
            name='culverts',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='curbSidewalkWidth',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='event',
            name='dateLastUpdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='deck',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='event',
            name='deckGeometry',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='deckStructureType',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='deckWidthOutToOut',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='deductCode',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='designLoad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='designatedInspectionFrequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='designatedNationalNetwork',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='directionOfTraffic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='facilityCarriedByStructure',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name='event',
            name='featuresIntersected',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='event',
            name='federalAgencyIndicator',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='federalLandsHighways',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='functionalClassOfInventoryRte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='futureAvgDailyTraffic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='highwayAgencyDistrict',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='event',
            name='highwaySystemOfInventoryRoute',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='historicalSignificance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='inspectionDate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='inventoryRating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='inventoryRoute',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='event',
            name='inventoryRouteSubrouteNumber',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='event',
            name='kilometerpoint',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='lanesOnUnderStructure',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='lengthOfMaximumSpan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='lengthOfStructureImprovement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='loc',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='maintenanceReponsibility',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='methodUsedToDetermineInventoryRating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='methodUsedToDetermineOperatingRating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='minLateralUnderclearOnLeft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='minLateralUnderclearOnRight',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='event',
            name='minVertClearOverBridgeRoadway',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='minimumNavigationVerticalClearanceVerticalLiftBridge',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='minimumVeriticalUnderclearance',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='event',
            name='navigationControl',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='navigationHorizontalClearance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='navigationVeriticalClearance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='nbisBridgeLength',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='numberOfApproachSpans',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='numberOfSpansInMainUnit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='operatingRating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='parallelStructureDesignation',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='pier',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='placeCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='roadwayImprovementCost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='scourCriticalBridges',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='skew',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='stateCode',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='event',
            name='statuswith10yearrule',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='structuralEvaluation',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='structureFlared',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='structureLength',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='structureNumber',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='event',
            name='structureTypeApproachSpans',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='event',
            name='structureTypeMain',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='event',
            name='strucutreOpenPostedClosed',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='substructure',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='sufficiencyRating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sufficiencyRatingAsteriskField',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='event',
            name='superstructure',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='temporaryStructureDesignation',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='toll',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='totalProjectCost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='trafficSafetyFeatures',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='event',
            name='typeLastUpdate',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='typeOfService',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='event',
            name='typeOfWork',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='event',
            name='underclearVerticalHorizontal',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='waterwayAdequacy',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='wearingSurface',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='event',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='yearBuilt',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='yearOfAverageDailyTraffic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='yearOfFutureAvgDailyTraffic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='yearOfImprovementCost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='yearReconstructed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
