# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171120_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='InventoryRTeMinVertClearance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='InventoryRteTotalHorzClearance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='approachRoadwayWidth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='bridgeRoadwayWithCurbToCurb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='dateLastUpdate',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='deckWidthOutToOut',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='inventoryRating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='lengthOfMaximumSpan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='minVertClearOverBridgeRoadway',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='operatingRating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='structureLength',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
