# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171122_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='approachRoadwayAlignment',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='channelChannelProtection',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='culverts',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='deckGeometry',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='deckStructureType',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='deductCode',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='federalAgencyIndicator',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='navigationControl',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='nbisBridgeLength',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='parallelStructureDesignation',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='scourCriticalBridges',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='statuswith10yearrule',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='structuralEvaluation',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='strucutreOpenPostedClosed',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='substructure',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='sufficiencyRating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='superstructure',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='temporaryStructureDesignation',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='typeLastUpdate',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='underclearVerticalHorizontal',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='waterwayAdequacy',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
