# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180110_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='structureLength',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
